### PR TITLE
Woscillators

### PR DESCRIPTION
**Pull request by vectorsize**
This PR adds a new oscillator type ([Woscillators](https://www.npmjs.com/package/@vectorsize/woscillators)) to the kitchen.

WeavesOscillators is a WebAudio version of Mutable Instrument's Plaits.

see [the official web site](https://vsaiz.me/woscillators/) for further details.

## Notes

Since `AudioWorklet` refuses to take a `standardized-audio-context` as context, a temporary fix had to be added to the `AudioContext` used in `audio-context.ts`. This is not a big issue since `audio-om` accepts a custom `AudioContext` upon instantiation, however, the `Audio` class expects the provided context to have a `createMediaStreamTrackSource` method (which only exists in certain browsers) so a mocked method was attached to the browser's context to fulfil that requirement.

### CODE REVIEW

**Comment by spencerudnick** [comment]
Do you get any audio from the new oscillator? I don't hear anything, maybe I don't understand how it's supposed to work...

I'm curious why the `standardized-audio-context` implementation doesn't work. It polyfills `AudioWorklet` and `createMediaStreamTrackSource` already.

**Comment by vectorsize** [comment]
> Do you get any audio from the new oscillator? I don't hear anything, maybe I don't understand how it's supposed to work...

Yes @spencerudnick , it should sound right away when you connect it
are you using chrome? we might have forgotten one fundamental thing and that is that as of today this only works in chrome, something I wrote at the top of my demos, and I even myself forgot hahaha. One solution for the kitchen is to only allow adding this type of oscillator to chrome users, and not in other browsers.

Some of the oscillator voices are not working as expected either, I'm working on fixing that at the moment.

**Comment by vectorsize** [comment]
> I'm curious why the standardized-audio-context implementation doesn't work. It polyfills AudioWorklet and createMediaStreamTrackSource already

me too, it doesn't really make sense, and it's frustrating that it wouldn't want to work with it, something to look deeper into.

**Comment by spencerudnick** [comment]
> are you using chrome?

I mainly dev and test in Firefox, but when it didn't work there I tried Chrome, which still didn't work for me.

**Comment by vectorsize** [comment]
oh I see now, I had this first time I implemented it too, try adding a regular oscillator first and then adding woscillators, I suspect it has to do with the graph not registering it properly? this time it was working right away for me thats why I submitted the PR 🤔

**Comment by spencerudnick** [comment]
The reason I opted to use `standardized-audio-context` is to ensure support on major browsers. If enabling `woscillators` to work with `standardized-audio-context` is desirable, then I could try it myself and submit a PR over there.

**Comment by vectorsize** [comment]
Yes and there is no reason why AudioWorklets shouldn't work on firefox, it should be fixable down the line.

**Comment by vectorsize** [comment]
There is an issue with the worklet on firefox at the moment, which is a bit tricky to debug as it is, but it should work since firefox implemented AudioWorklet already

**Comment by spencerudnick** [comment]
I guess one way for me to test would be to revert the commit which patches the audio context.

**Comment by vectorsize** [comment]
you can comment those lines too, but i'm ok of you rather not have it half working as it is at the moment in the main branch

**Pull request merged**
